### ISSUE TITLE
loadAd() not working

### ISSUE THREAD

**Issue by cokepizza** [ammarahm-ed/react-native-admob-native-ads#136]
I followed the migration docs after upgrading to 0.3.9 => 0.4.0, but I can't render ad because there is no loadAd function. The same is true for your example.

"_nativeAdRef$current2.loadAd is not a function"

How can I run the loadAd function?

**Comment by cokepizza** [comment]
I don't know if there was a cache, but after I cleared the package-lock.json and Podfile.lock a few times and reinstalled, I confirmed that the loadAd function works.
