### ISSUE TITLE
com.google.android.gms.ads.formats.AdChoicesView

### ISSUE THREAD

**Issue by tariqproxym** [ammarahm-ed/react-native-admob-native-ads#148]
react-native-admob-native-ads\android\src\main\java\com\ammarahmed\rnadmob\nativeads\RNAdmobAdChoicesManager.java:8: error: cannot find symbol
import com.google.android.gms.ads.formats.**AdChoicesView**

**Comment by RapunzlFounder** [comment]
I'm having this same problem when running on real android devices since the update to 0.4.0

**Comment by losthakkun** [comment]
To fix this...

inside node modules/react-native-admob-native-ads/android/build.gradle
comment this line
implementation "com.google.android.gms:play-services-ads:+"

you only need to comment on that line, do not add version 19.8.0

**Comment by tariqproxym** [comment]
@losthakkun Actually comment this line did not solve the issue. 
but adding 19.8.0 solves it.

if I comment it should id do extra steps like clear cache or anything else

**Comment by juceda** [comment]
Commenting the line is a wrong answer.  Because the module needs that dependency.

Also this module (react-native-admob-native-ads) needs an update to handle that issue,  Google SDK v20 changed package names so broke v <=0.4.0

I suggest to change the line to:

implementation "com.google.android.gms:play-services-ads:19.+"

so you will use the latest 19.x version that is still compatible with 0.4.0

> @losthakkun Actually comment this line did not solve the issue.
> but adding 19.8.0 solves it.
> 
> if I comment it should id do extra steps like clear cache or anything else

**Comment by Bsingh2697** [comment]
Replace this
          implementation "com.google.android.gms:play-services-ads:+"
with this
          implementation("com.google.android.gms:play-services-ads:19.8.0") { force = true; }

**Comment by nicoloso100** [comment]
> Replace this
> implementation "com.google.android.gms:play-services-ads:+"
> with this
> implementation("com.google.android.gms:play-services-ads:19.8.0") { force = true; }

worked for me

**Comment by ammarahm-ed** [comment]
fixed on master.
